name: Main

on: [push]

jobs:

  Build_test_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
          cache: true

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
        
      - name: Build and publish Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          image-name: schuett-webapp-api
          additional-image-tags: ${{ github.run_id }}
